repos:
- repo: https://github.com/python/black
  rev: stable
  hooks:
  - id: black
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: master
  hooks:
  - id: check-added-large-files
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: check-json
  - id: end-of-file-fixer
  - id: trailing-whitespace
